[env:nucleo_f446re]
platform      = ststm32
board         = nucleo_f446re
framework     = arduino
monitor_speed = 115200
upload_protocol = mbed
build_flags   = -D HAL_UART_MODULE_ENABLED
build_src_filter = +<main.cpp> +<stalk.cpp>

[env:calibrate]
platform      = ststm32
board         = nucleo_f446re
framework     = arduino
monitor_speed = 115200
upload_protocol = mbed
build_flags   = -D HAL_UART_MODULE_ENABLED
; Include only the calibration sketch, not main.cpp
build_src_filter = +<stalk.cpp> +<calibrate.cpp>
